spring:
  datasource:
    username: test
    password: test
    url: jdbc:h2:~/MusicBayTesting
    driver-class-name: org.h2.Driver
    #data: classpath:data/test.sql
    #initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      path: /MusicBayTestingDB
server:
  port: 4444