spring:
  datasource:
    username: test
    password: test
    url: jdbc:h2:~/MusicBayTesting
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      path: /MusicBayTestingDB
      enabled: true
      settings:
        web-allow-others: true
server:
  port: 4444