spring:
  datasource:
    username: test
    password: test
    url: jdbc:h2:~/MusicBayTesting
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      path: /MusicBayTestingDB
  #sql:
   # init:
    #  mode: always
     # data-locations: classpath:data/test.sql
server:
  port: 4444